# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  galyonj.com:
    site_hosts:
      - canonical: galyonj.dev
        redirects:
          - www.galyonj.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: galyon.jb@gmail.com
    admin_user: jgalyon
    db_name: galyonj_dev_db
    db_prefix: morrigan_
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
